code = "MVE255"
title = "Flervariabelanalys och partiella differentialekvationer"
examiner = "Anders Logg"
department = "Matematiska vetenskaper"
school = "Chalmers tekniska högskola"
phone = "031--772 5346"

_answer = "svar"
_code = "kurskod"
_exam = "tentamen"
_examiner = "examinator"
_good_luck = "lycka till"
_part = "del"
_phone = "telefon"
_solutions = "lösningar"
